services:
  grafana:
    container_name: 'embrace-grafana'
    build:
      context: ./.config
      args:
        grafana_version: ${GRAFANA_VERSION:-latest}
    ports:
      - 3000:3000/tcp
    volumes:
      - ./dist:/var/lib/grafana/plugins/embrace-embrace-app
      - ./provisioning:/etc/grafana/provisioning
